# Project Information
site_name: PagerDuty Security Training
site_description: Public versions of PagerDuty's employee security training courses.
site_author: PagerDuty, Inc.
site_url: https://sudo.pagerduty.com/

# Repository
repo_url: https://github.com/pagerduty/security-training

# Copyright
copyright: 'Copyright &copy; PagerDuty, Inc.'

# Theme
theme:
  name: pagerduty
  title: 'Security Training'
  custom_dir: overrides  # We add some extra things to the homepage

# Contents
nav:
  - Overview: 'index.md'
  - For Everyone: 'for_everyone/index.md'
  - For Everyone (Part II): 'for_everyone_part_ii/index.md'
  - For Engineers: 'for_engineers/index.md'

# Analytics
google_analytics: ['UA-8759953-1', 'auto']

# Extensions
markdown_extensions:
  - toc:
      permalink: '#'
  - sane_lists:
  - admonition:
  - meta:
  - pymdownx.details:
  - pymdownx.extra:
  - pymdownx.mark:
  - pymdownx.tilde:
  - pymdownx.highlight:
  - pymdownx.superfences:
  - pymdownx.tabbed:

# Development URL, bind to local only.
dev_addr: '127.0.0.1:8000'
