# Project Information
site_name: PagerDuty Security Training
site_description: Public versions of PagerDuty's employee security training courses.
site_author: PagerDuty, Inc.
site_favicon: 'assets/img/favicon.png'
site_url: https://sudo.pagerduty.com

# Copyright
copyright: 'Copyright &copy; PagerDuty, Inc.'

# Theme
theme: 'material'
theme_dir: 'theme'
extra_css: ['assets/css/pagerduty.css','assets/css/custom.css']
extra:
  favicon: 'assets/img/favicon.png'
  logo: 'assets/img/icon.png'
  cover: 'assets/img/cover.png'
  palette:
    primary: 'green'
    accent: 'blue grey'
  author:
    github: 'PagerDuty'
    twitter: 'PagerDuty'

# Contents
pages:
  - Overview: 'index.md'
  - For Everyone: 'for_everyone/index.md'
  - For Engineers: 'for_engineers/index.md'

# Analytics
google_analytics: ['UA-8759953-1', 'auto']

# Extensions
markdown_extensions:
  - toc:
      permalink: '#'
  - sane_lists:
  - admonition:
  - meta:
  - pymdownx.details:
  - pymdownx.extra:
  - pymdownx.mark:
  - pymdownx.tilde:
